# Generated by Django 6.0.3 on 2026-04-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='apoderado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colegio.apoderado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='is_apoderado_principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='parentesco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
