# Generated by Django 6.0.3 on 2026-04-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_matricula_apoderado_matricula_is_apoderado_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='apoderado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='is_apoderado_principal',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='parentesco',
        ),
        migrations.AddField(
            model_name='matricula',
            name='estado',
            field=models.CharField(default='Activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(auto_now_add=True),
        ),
    ]
