# Generated by Django 6.0.3 on 2026-06-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_remove_matricula_apoderado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado_curso',
            field=models.BooleanField(default=True, verbose_name='Curso Activo'),
        ),
    ]
