# Generated by Django 6.0.5 on 2026-06-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_curso_estado_curso'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('nivel', 'seccion'), name='uq_curso_nivel_seccion'),
        ),
    ]
