# Generated by Django 6.0.5 on 2026-06-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0005_curso_uq_curso_nivel_seccion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curso',
            name='uq_curso_nivel_seccion',
        ),
        migrations.AddField(
            model_name='curso',
            name='ciclo',
            field=models.CharField(choices=[('Parvulario', 'Parvulario / Pre-Kinder / Kinder'), ('Básico', 'Enseñanza Básica'), ('Medio', 'Enseñanza Media')], default='Básico', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado_curso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.PositiveIntegerField(help_text='Ejemplo: 1, 2, 3...'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='seccion',
            field=models.CharField(help_text='Ejemplo: A, B, C...', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('ciclo', 'nivel', 'seccion'), name='uq_curso_ciclo_nivel_seccion'),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre_curso',
        ),
    ]
