# Generated by Django 6.0.5 on 2026-06-03 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0006_remove_curso_uq_curso_nivel_seccion_curso_ciclo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curso',
            name='uq_curso_ciclo_nivel_seccion',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='colegio.curso', verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='asignaturas', to='colegio.docente', verbose_name='Docentes a Cargo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='estado_asignatura',
            field=models.BooleanField(choices=[(True, 'Activa'), (False, 'En Revisión')], default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre_asignatura',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ciclo',
            field=models.CharField(choices=[('BASICA', 'Enseñanza Básica'), ('MEDIA', 'Enseñanza Media')], max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='seccion',
            field=models.CharField(max_length=2),
        ),
    ]
