# Generated by Django 6.0.6 on 2026-06-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0007_alter_alumno_id_alter_alumnoapoderado_id_and_more'),
        ('colegio', '0007_remove_curso_uq_curso_ciclo_nivel_seccion_and_more'),
    ]

    operations = [
    ]
