# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0010_alter_alumno_id_alter_alumnoapoderado_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ciclo',
            field=models.CharField(
                choices=[
                    ('KINDER', 'Kinder'),
                    ('BASICA', 'Enseñanza Básica'),
                    ('MEDIA', 'Enseñanza Media'),
                ],
                max_length=10,
            ),
        ),
    ]
