# Generated by Django 4.1.2 on 2026-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0011_alter_curso_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='apoderados',
            field=models.ManyToManyField(blank=True, related_name='matriculas', to='colegio.apoderado'),
        ),
    ]
