# Generated by Codex on 2026-07-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("colegio", "0012_matricula_apoderados"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="profesor_jefe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos_jefatura",
                to="colegio.docente",
            ),
        ),
    ]
