# Generated by Django 6.0.5 on 2026-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0014_alter_alumno_id_alter_alumnoapoderado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpostulacion',
            name='ciclo_postulacion',
            field=models.CharField(blank=True, choices=[('KINDER', 'Kinder'), ('BASICA', 'Enseñanza Básica'), ('MEDIA', 'Enseñanza Media')], max_length=10, null=True, verbose_name='Ciclo al que postula'),
        ),
        migrations.AddField(
            model_name='solicitudpostulacion',
            name='nivel_postulacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nivel al que postula'),
        ),
    ]
