# Generated by Django 6.0.5 on 2026-09-21 19:57

import colegio.tenancy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0015_solicitudpostulacion_ciclo_postulacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Identificador en la dirección propia del establecimiento.', max_length=80, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', colegio.tenancy.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='alumnoapoderado',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='docente',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='nota',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='solicitudpostulacion',
            name='institucion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='colegio.institucion'),
        ),
    ]
