# Generated by Django 6.0.5 on 2026-09-21 20:01

import colegio.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colegio', '0017_institucion_paso2_asignar_datos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodoacademico',
            name='uq_periodo_anio_semestre',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='alumnoapoderado',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email_institucional',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='docente',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='solicitudpostulacion',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(help_text='Formato: 12.345.678-9', max_length=12, validators=[colegio.validators.validar_rut_chileno]),
        ),
        migrations.AddConstraint(
            model_name='apoderado',
            constraint=models.UniqueConstraint(fields=('institucion', 'email'), name='uq_apoderado_institucion_email'),
        ),
        migrations.AddConstraint(
            model_name='docente',
            constraint=models.UniqueConstraint(fields=('institucion', 'email_institucional'), name='uq_docente_institucion_email'),
        ),
        migrations.AddConstraint(
            model_name='periodoacademico',
            constraint=models.UniqueConstraint(fields=('institucion', 'anio', 'semestre'), name='uq_periodo_institucion_anio_semestre'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('institucion', 'rut'), name='uq_usuario_institucion_rut'),
        ),
    ]
