# Generated by Django 6.0.5 on 2026-09-21 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0018_institucion_paso3_obligatoria_y_unicidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRUEBA', 'Prueba'), ('RUBRICA', 'Rúbrica'), ('MATERIAL', 'Material de estudio')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True, help_text='Objetivo de Aprendizaje (OA) al que apunta.')),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('contenido_ia', models.JSONField()),
                ('contenido', models.JSONField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=10)),
                ('porcentaje_corregido', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos_ia', to='colegio.cargaacademica')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos_ia', to='colegio.docente')),
                ('institucion', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
