# Generated by Django 6.0.5 on 2026-09-21 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0019_instrumento_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField()),
                ('correctas', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('leida_con_ia', models.BooleanField(default=False)),
                ('ajustes_docente', models.PositiveSmallIntegerField(default=0, help_text='Respuestas que el docente cambió respecto de la lectura de la IA.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_prueba', to='colegio.alumno')),
                ('institucion', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='colegio.institucion')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='colegio.instrumentoia')),
                ('nota_registrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='colegio.nota')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
